FROM alpine:latest

RUN apk add --no-cache dnsmasq inotify-tools
COPY dnsmasq.conf /etc/dnsmasq.conf
COPY reload.sh /reload.sh

VOLUME [ "/etc/dnsmasq.d/" ]
EXPOSE 53/TCP
EXPOSE 53/UDP

CMD [ "/reload.sh" ]